# Generated by Django 4.0.5 on 2022-06-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='send_message',
            new_name='send_messages',
        ),
    ]
